# The big one -- training. You bad better not read this.
# This file is based on
#   https://docs.pytorch.org/tutorials/beginner/data_loading_tutorial.html
import numpy                     as np
import torch                     as pytorch
import torchvision.transforms.v2 as T

from os.path          import join, exists
from json             import load, dumps
from torch            import tensor, float32, long, device, nn, seed, manual_seed, argmax, no_grad, cuda, Tensor 
from torch.optim      import AdamW, lr_scheduler 
from torch.cuda       import is_available
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from sys              import argv
from tqdm             import tqdm
from datetime         import datetime
from os               import makedirs
from shutil           import rmtree
from random           import seed

from tools.protomodel import *
from tools.evalgen    import int_GenerateConfusionMatrix


def int_GetModelType(mdlfile: str) -> tuple[int, type]:
    i = int(mdlfile)

    match i:
        case 1:
            return i, GazeRegEyeModel1
        case 2:
            return i, GazeRegEyeModel2
        case 3:
            return i, GazeRegEyeModel3
        case 4:
            return i, GazeRegEyeModel4
        case 5:
            return i, GazeRegEyeModel5
        case 6:
            return i, GazeRegEyeModel6
        case 7:
            return i, GazeRegEyeModel7
        case 10:
            return i, GazeRegEyeModel10
        
        case 100:
            return i, GazeRegEyeModel100
        case 101:
            return i, GazeRegEyeModel101
        case 102:
            return i, GazeRegEyeModel102
        case 103:
            return i, GazeRegEyeModel103
        case 104:
            return i, GazeRegEyeModel104
        case 106:
            return i, GazeRegEyeModel106
        case 107:
            return i, GazeRegEyeModel107
        
        case 200:
            return i, GazeRegEyeModel200
        case 201:
            return i, GazeRegEyeModel201
        
    return i, None


# BEGIN Generated by ChatGPT Ver. 5.5.
def int_FormatTimeDelta(td) -> str:
    total_seconds = int(td.total_seconds())

    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)

    return f'{hours:02}h{minutes:02}m{seconds:02}s'
# END Generated by ChatGPT Ver. 5.5.


def int_OutputEvaluationStatistics(
    dir:     str,
    id:      str,
    t:       datetime,
    bep:     int,
    hy:      dict[str, any],
    ds:      dict[str, any],
    losses:  tuple[list, list, list],
    accs:    tuple[list, list, list],
    cnf:     tuple[list, list, list, list, list, list],
    epstats: dict
) -> None:
    # Make result directory.
    if not exists(dir):
        makedirs(dir)

    dt = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

    tl, el, tel = losses
    tlx, tly    = zip(*tl)
    elx, ely    = zip(*el)
    tex, tey    = zip(*tel)
    ta, ea, tea = accs
    tax, tay    = zip(*ta)
    eax, eay    = zip(*ea)
    teax, teay  = zip(*tea)

    # Write statistics.
    with open(f'{dir}/Ev_Stats_Mdl{id}_{dt}.json', 'w') as f:
        f.write(dumps({
            't':          int_FormatTimeDelta(t),
            'dt':         dt,
            'bep':        bep,
            'hyper':      hy,
            'dataset':    ds,
            'trLossesX':  tlx,
            'trLossesY':  tly,
            'trELossesX': tex,
            'trELossesY': tey,
            'evLossesX':  elx,
            'evLossesY':  ely,
            'trAccX':     tax,
            'trAccY':     tay,
            'trEAccX':    teax,
            'trEAccY':    teay,
            'evAccX':     eax,
            'evAccY':     eay,
            'cnf':       {
                'trYReal':   cnf[0],
                'trYPred':   cnf[1],
                'evYReal':   cnf[2],
                'evYPred':   cnf[3],
                'evTrEReal': cnf[4],
                'evTrEPred': cnf[5]
            },
            'epochs': epstats
        }, indent=4))

        print(f'Wrote statistics to {f.name}.')


class GazeRegDataset(Dataset):
    def __init__(self, cfg, dir, new, split=(0.8, 0.2), rev=False, eval=False, augment=False, merge=False, sampleRate=1, evalSessions=None):
        # (1) Load dataset listing file.
        try:
            with open(cfg, 'r') as file:
                self._config = load(file)
        except:
            print(f'Could not read dataset listing file "{cfg}". Aborting.')

            return
        self._nSessions = self._config['nsess']
        self._dir       = dir
        self._eval      = eval
        self._tr        = T.Compose([
            T.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.1),
            T.GaussianBlur(kernel_size=3, sigma=(0.1, 1.0))
        ])
        self._augm      = augment
        self._new       = new
        self._split     = split
        self._merge     = merge
        if self._merge:
            for k in self._config['sessions'].keys():
                for v in self._config['sessions'][k]:
                    v[-1] = v[-1] if v[-1] == 0 else v[-1] - 1
                
        # Get all sessions in the listing.
        self._sessions = list(self._config['sessions'].keys())

        # (2) Get training set.
        if evalSessions is None:
            self._trainSess = self._sessions[int(split[1]*self._nSessions):] if rev else self._sessions[0:int(split[0]*self._nSessions)]
        else:
            self._trainSess = [x for x in self._sessions if x not in evalSessions]
        self._trainData = []
        for s in self._trainSess:
            v = self._config['sessions'][s]

            self._trainData.extend(v)

        # (3) Get eval set.
        if evalSessions is None:
            self._evalSess = self._sessions[0:int(split[1]*self._nSessions)] if rev else self._sessions[int(split[0]*self._nSessions):]
        else:
            self._evalSess = [x for x in self._sessions if x in evalSessions]
        self._evalData = []
        for s in self._evalSess:
            v = self._config['sessions'][s]

            self._evalData.extend(v)

        if sampleRate != 1:
            if sampleRate > 1:
                self._trainData = [x for i, x in enumerate(self._trainData, 1) if i % sampleRate == 0]
            elif sampleRate == -2:
                cTr, _, _ = self.getClassCounts()
                minClsIdx = cTr.index(min(cTr))
                self._trainData = [x for i, x in enumerate(self._trainData, 1) if i % (5 if x[-1] != cTr[minClsIdx] else 2) == 0]


        # Print some stats.
        print(f'Training set:   {self._trainSess} ({len(self._trainSess)}/{self._nSessions} sessions), {len(self._trainData)}/{self._config["ndata"]} items.')
        print(f'Evaluation set: {self._evalSess}({len(self._evalSess)}/{self._nSessions} sessions), {len(self._evalData)}/{self._config["ndata"]} items.')


    def __len__(self):
        return len(self._trainData) if not self._eval else len(self._evalData)


    def __getitem__(self, idx):
        if not self._eval:
            if not self._new:
                ln, rn, lbl = self._trainData[idx]
            else:
                ln, rn, lmn, pn, lbl = self._trainData[idx]
        else:
            if not self._new:
                ln, rn, lbl = self._evalData[idx]
            else:
                ln, rn, lmn, pn, lbl = self._evalData[idx]

        if not self._eval and self._augm:
            s = seed()
            l = tensor(np.load(join(self._dir, ln)), dtype=float32).unsqueeze(0) / 255.0
            r = tensor(np.load(join(self._dir, rn)), dtype=float32).unsqueeze(0) / 255.0

            manual_seed(s)
            l = self._tr(l)
            manual_seed(s)
            r = self._tr(r)
        else:
            l = tensor(np.load(join(self._dir, ln)), dtype=float32).unsqueeze(0) / 255.0
            r = tensor(np.load(join(self._dir, rn)), dtype=float32).unsqueeze(0) / 255.0
        y = tensor(lbl, dtype=long)

        if self._new:
            lm = tensor(np.load(join(self._dir, lmn)), dtype=float32)
            p  = tensor(np.load(join(self._dir, pn)), dtype=float32)

            return l, r, lm, p, y
        
        return l, r, y
    

    def getDatasetStats(self) -> dict:
        return {
            'sess':      self._sessions,
            'nSess':     self._nSessions,
            'evalSess':  self._evalSess,
            'nEvalSess': len(self._evalSess),
            'evData':    len(self._evalData),
            'trainSess': self._trainSess,
            'nTrSess':   len(self._trainSess),
            'trData':    len(self._trainData),
            'split':     [self._split[0], self._split[1]],
            'clsDist':   None
        }
    
    def getClassWeights(self) -> Tensor:
        # https://naadispeaks.blog/2021/07/31/handling-imbalanced-classes-with-weighted-loss-in-pytorch/
        # Get number of samples per class.
        c, _, _ = self.getClassCounts()
        # Get total number of samples.
        tot = len(self._trainData)

        return tensor([1.0 - i / tot for i in c], dtype=float32)
    
    def getClassCounts(self) -> tuple[list, list, list]:
        cTot = [0, 0, 0, 0] if not self._merge else [0, 0, 0]
        cTr  = [0, 0, 0, 0] if not self._merge else [0, 0, 0]
        cEv  = [0, 0, 0, 0] if not self._merge else [0, 0, 0]

        for x in self._trainData:
            l = x[-1]

            cTr[l]  += 1
            cTot[l] += 1

        for x in self._evalData:
            l = x[-1]

            cEv[l]  += 1
            cTot[l] += 1

        return cTr, cEv, cTot
    

    def getClassSampleWeights(self) -> Tensor:
        return tensor([1.25, 2.0, 1.0, 1.0] if not self._merge else [(2.0 + 1.25) / 2, 1.0, 1.0], dtype=float32)


    def getSampleWeights(self) -> Tensor:
        clsW   = self.getClassSampleWeights()
        yReals = tensor([y for _, _, _, _, y in self._trainData], dtype=long)

        sWeights = clsW[yReals]
        return sWeights


    def getRawEvaluationSampleList(self):
        return self._evalData



if __name__ == '__main__':
    # Parse command-line.
    startT = datetime.now()
    nam  = argv[1]
    cfg  = argv[2]
    dir  = argv[3]
    ty   = argv[4]
    sout = argv[5]
    aug  = '-a' in argv or '--augment' in argv
    rev  = '-r' in argv or '--reverse' in argv
    det  = '-d' in argv or '--determ'  in argv
    ovs  = '-o' in argv
    mer  = '-m' in argv
    uds  = '-u' in argv

    # Initialize PRNGs with fixed random seed if training in deterministic mode.
    __seed = 0x04012002
    if det:
        manual_seed(__seed)
        seed(__seed)
        np.random.seed(__seed)
        cuda.manual_seed(__seed)
        cuda.manual_seed_all(__seed)

    n, ModelType = int_GetModelType(ty)
    new          = n >= 100

    if exists(sout):
        rmtree(sout)
    makedirs(sout)

    # Main hyperparameters.
    epochs = 30
    opt    = AdamW
    lr     = 1e-4
    wd     = 1e-4
    bs     = 32
    es     = False
    esd    = 1e-4
    pat    = 5
    b1     = 0.9
    b2     = 0.999
    sr     = 10

    # Initialize datasets.
    trDs = GazeRegDataset(cfg, dir, new=new, rev=rev, eval=False, augment=aug, merge=mer, sampleRate=sr if uds else 1)
    tEDs = GazeRegDataset(cfg, dir, new=new, rev=rev, eval=False, merge=mer)
    evDs = GazeRegDataset(cfg, dir, new=new, rev=rev, eval=True, merge=mer)
    smW  = trDs.getSampleWeights()
    csmW = trDs.getClassSampleWeights() if ovs else tensor([1.0, 1.0, 1.0, 1.0], dtype=long)
    if ovs:
        sampl = WeightedRandomSampler(smW, len(smW), True)
    else:
        sampl = None
    trLd = DataLoader(trDs, batch_size=bs, shuffle=not ovs, num_workers=4, sampler=sampl)
    tELd = DataLoader(trDs, batch_size=bs, shuffle=False, num_workers=4)
    evLd = DataLoader(evDs, batch_size=bs, shuffle=False, num_workers=4)
    dev  = device('cuda' if is_available() else 'cpu')

    # Initialize more training parameters.
    clsW = tensor([
        1.0,
        2.0,
        1.0,
        1.0
    ], dtype=float32).to(dev)
    crit = nn.CrossEntropyLoss(weight=clsW) if not is_available() else nn.CrossEntropyLoss(weight=clsW).cuda()
    mdl  = ModelType(mer).to(dev)
    opt  = opt(mdl.parameters(), lr=lr, weight_decay=wd)
    dsSt = trDs.getDatasetStats()
    dsCt = trDs.getClassCounts()
    scheduler = lr_scheduler.StepLR(opt, step_size=5, gamma=0.1)

    # Add class distribution to dataset stats.
    """
    dsSt['clsDist'] = {
        'tr': {
            0: [dsCt[0][0], dsCt[0][0] / sum(x for x in dsCt[0]), dsCt[0][0] / dsCt[2][0]], # abs, frac/cat, frac/tot
            1: [dsCt[0][1], dsCt[0][1] / sum(x for x in dsCt[0]), dsCt[0][1] / max(1, dsCt[2][1])],
            2: [dsCt[0][2], dsCt[0][2] / sum(x for x in dsCt[0]), dsCt[0][2] / dsCt[2][2]],
            3: [dsCt[0][3], dsCt[0][3] / sum(x for x in dsCt[0]), dsCt[0][3] / dsCt[2][3]]
        },
        'ev': {
            0: [dsCt[1][0], dsCt[1][0] / sum(x for x in dsCt[1]), dsCt[1][0] / dsCt[2][0]],
            1: [dsCt[1][1], dsCt[1][1] / sum(x for x in dsCt[1]), dsCt[1][1] / max(1, dsCt[2][1])], 
            2: [dsCt[1][2], dsCt[1][2] / sum(x for x in dsCt[1]), dsCt[1][2] / dsCt[2][2]],
            3: [dsCt[1][3], dsCt[1][3] / sum(x for x in dsCt[1]), dsCt[1][3] / dsCt[2][3]]
        }, 
        'tot': {
            0: [dsCt[2][0], dsCt[2][0] / sum(x for x in dsCt[2])], # abs, frac/tot
            1: [dsCt[2][1], dsCt[2][1] / sum(x for x in dsCt[2])], 
            2: [dsCt[2][2], dsCt[2][2] / sum(x for x in dsCt[2])],
            3: [dsCt[2][3], dsCt[2][3] / sum(x for x in dsCt[2])]
        }
    }
    """
    dsSt['clsDist'] = {}

    hyperP = {
        'nep': epochs,
        'bs':  bs,
        'opt': {
            'id': opt.__class__.__name__,
            'lr': lr,
            'wd': wd,
            'b1': b1,
            'b2': b2
        },
        'rev': rev,
        'aug': aug,
        'es':  es,
        'esd': esd,
        'p':   pat,
        'lfn': crit.__class__.__name__,
        """
        'wg':  {
            0: clsW[0].item(),
            1: clsW[1 if not mer else 0].item(),
            2: clsW[2 if not mer else 1].item(),
            3: clsW[3 if not mer else 2].item()
        },
        'csw': {
            0: csmW[0].item(),
            1: csmW[1].item(),
            2: csmW[2].item(),
            3: csmW[3].item()
        },
        """
        'mer':  mer,
        'seed': __seed
    }
    epStats = {}

    if is_available():
        print('info: Running on CUDA device.')
    bestState  = None
    bestEp     = 0
    totTrLoss  = []
    totTrELoss = []
    totEvLoss  = []
    totTrAcc   = []
    totTrEAcc  = []
    totEvAcc   = []
    totTYReal  = []
    totTYPred  = []
    totTEYReal = []
    totTEYPred = []
    totEYReal  = []
    totEYPred  = []
    try:
        bEvLoss  = float('inf')
        patience = pat # 5 before
        wait     = 0

        for e in range(epochs):
            mdl.train()
            trLoss, evLoss, trCorr, trTot, evCorr, evTot = 0.0, 0.0, 0, 0, 0, 0
            trELoss, trEAcc, trECorr, trETot = 0.0, 0.0, 0, 0
            currTYReal  = []
            currTYPred  = []
            currTEYReal = []
            currTEYPred = []
            currEYReal  = []
            currEYPred  = []
            clsStats    = {
                'tr': {
                    0: [0, 0, 0.0], # corr, total, acc
                    1: [0, 0, 0.0],
                    2: [0, 0, 0.0],
                    3: [0, 0, 0.0],
                },
                'tre': {
                    0: [0, 0, 0.0], # corr, total, acc
                    1: [0, 0, 0.0],
                    2: [0, 0, 0.0],
                    3: [0, 0, 0.0],
                },
                'ev': {
                    0: [0, 0, 0.0],
                    1: [0, 0, 0.0],
                    2: [0, 0, 0.0],
                    3: [0, 0, 0.0],
                },
            }

            # Train one epoch.
            t = tqdm(trLd, desc=f"[tr] Epoch {e + 1}/{epochs}")
            for i in t:
                if not new:
                    l, r, y = i
                else:
                    l, r, lm, p, y = i

                    lm, p = lm.to(dev), p.to(dev)
                l, r, y = l.to(dev), r.to(dev), y.to(dev)

                opt.zero_grad()
                if not new:
                    res = mdl(l, r)
                else:
                    res = mdl(l, r, lm, p)
                cLoss   = crit(res, y)
                resM    = argmax(res, dim=1)
                trTot  += resM.size(0)
                trCorr += (resM == y).sum().item()

                # Collect stats for confusion matrix and class stats.
                for yr, yp in zip(y, resM):
                    currTYReal.append(yr.item())
                    currTYPred.append(yp.item())
                    totTYReal.append(yr.item())
                    totTYPred.append(yp.item())

                    clsStats['tr'][yr.item()][0] += yr.item() == yp.item()
                    clsStats['tr'][yr.item()][1] += 1
                    clsStats['tr'][yr.item()][2] = clsStats['tr'][yr.item()][0] / clsStats['tr'][yr.item()][1]

                cLoss.backward()
                opt.step()
                trLoss += cLoss.item() * y.size(0)
                t.set_postfix(loss=cLoss.item())

            # Write live training confusion matrix.
            if not exists(join(sout, 'livecnf/tr')):
                makedirs(join(sout, 'livecnf/tr'))
            int_GenerateConfusionMatrix(currTYReal, currTYPred, 'Tr', join(sout, 'livecnf/tr'), 'true', e + 1, 'LiveCurr_', mer=mer)
            int_GenerateConfusionMatrix(totTYReal, totTYPred, 'Tr', join(sout, 'livecnf/tr'), 'true', e + 1, 'LiveTot_', mer=mer)

            # Evaluate epoch.
            with no_grad():
                mdl.eval()

                t = tqdm(tELd, desc=f"[tr-ev] Epoch {e + 1}/{epochs}")
                for i in t:
                    if not new:
                        l, r, y = i
                    else:
                        l, r, lm, p, y = i

                        lm, p = lm.to(dev), p.to(dev)
                    l, r, y = l.to(dev), r.to(dev), y.to(dev)

                    if not new:
                        res = mdl(l, r)
                    else:
                        res = mdl(l, r, lm, p)
                    cLoss    = crit(res, y)
                    resM     = argmax(res, dim=1)
                    trETot  += y.size(0)
                    trECorr += (resM == y).sum().item()
                    trELoss += cLoss.item() * y.size(0)

                    # Collect stats for confusion matrix and class stats.
                    for yr, yp in zip(y, resM):
                        currTEYReal.append(yr.item())
                        currTEYPred.append(yp.item())
                        totTEYReal.append(yr.item())
                        totTEYPred.append(yp.item())

                        clsStats['tre'][yr.item()][0] += yr.item() == yp.item()
                        clsStats['tre'][yr.item()][1] += 1
                        clsStats['tre'][yr.item()][2] = clsStats['tre'][yr.item()][0] / clsStats['tre'][yr.item()][1]

                t = tqdm(evLd, desc=f"[ev-ev] Epoch {e + 1}/{epochs}")
                for i in t:
                    if not new:
                        l, r, y = i
                    else:
                        l, r, lm, p, y = i

                        lm, p = lm.to(dev), p.to(dev)
                    l, r, y = l.to(dev), r.to(dev), y.to(dev)

                    if not new:
                        res = mdl(l, r)
                    else:
                        res = mdl(l, r, lm, p)
                    cLoss   = crit(res, y)
                    resM    = argmax(res, dim=1)
                    evTot  += y.size(0)
                    evCorr += (resM == y).sum().item()
                    evLoss += cLoss.item() * y.size(0)

                    # Collect stats for confusion matrix and class stats.
                    for yr, yp in zip(y, resM):
                        currEYReal.append(yr.item())
                        currEYPred.append(yp.item())
                        totEYReal.append(yr.item())
                        totEYPred.append(yp.item())

                        clsStats['ev'][yr.item()][0] += yr.item() == yp.item()
                        clsStats['ev'][yr.item()][1] += 1
                        clsStats['ev'][yr.item()][2] = clsStats['ev'][yr.item()][0] / clsStats['ev'][yr.item()][1]

            # Write live evaluation confusion matrix.
            if not exists(join(sout, 'livecnf/trev')):
                makedirs(join(sout, 'livecnf/trev'))
            int_GenerateConfusionMatrix(currTEYReal, currTEYPred, 'TrEv', join(sout, 'livecnf/trev'), 'true', e + 1, 'LiveCurr_', mer=mer)
            int_GenerateConfusionMatrix(totTEYReal, totTEYPred, 'TrEv', join(sout, 'livecnf/trev'), 'true', e + 1, 'LiveTot_', mer=mer)

            # Write live evaluation confusion matrix.
            if not exists(join(sout, 'livecnf/ev')):
                makedirs(join(sout, 'livecnf/ev'))
            int_GenerateConfusionMatrix(currEYReal, currEYPred, 'Ev', join(sout, 'livecnf/ev'), 'true', e + 1, 'LiveCurr_', mer=mer)
            int_GenerateConfusionMatrix(totEYReal, totEYPred, 'Ev', join(sout, 'livecnf/ev'), 'true', e + 1, 'LiveTot_', mer=mer)
            scheduler.step()

            avgTrLoss  = trLoss / trTot
            avgValLoss = evLoss / evTot
            avgTrELoss = trELoss / trETot
            trainAcc   = trCorr / trTot
            trEAcc     = trECorr / trETot
            evAcc      = evCorr / evTot
            print(f"Epoch {e + 1}:")
            print(f'  Training:   L={avgTrLoss:.4f}, A={(trainAcc * 100):.4f}%')
            print(f'  Train-Eval: L={avgTrELoss:.4f}, A={(trEAcc * 100):.4f}%')
            print(f'  Evaluation: L={avgValLoss:.4f}, A={(evAcc * 100):.4f}%')

            # Collect per-epoch statistics.
            epStats[e + 1] = {
                'trLoss':   avgTrLoss,
                'trELoss':  avgTrELoss,
                'evLoss':   avgValLoss,
                'trCorr':   trCorr,
                'trTot':    trTot,
                'trAcc':    trainAcc,
                'trECorr':  trECorr,
                'trETot':   trETot,
                'trEAcc':   trEAcc,
                'evCorr':   evCorr,
                'evTot':    evTot,
                'evAcc':    evAcc,
                'tYReal':   currTYReal,
                'tYPred':   currTYPred,
                'trEYReal': currTEYReal,
                'trEYPred': currTEYPred,
                'eYReal':   currEYReal,
                'eYPred':   currEYPred,
                'clsSt':    clsStats
            }

            # Collect global statistics.
            totTrLoss.append(((e + 1),  avgTrLoss))
            totEvLoss.append(((e + 1),  avgValLoss))
            totTrELoss.append(((e + 1), avgTrELoss))
            totTrAcc.append(((e + 1),   trainAcc))
            totEvAcc.append(((e + 1),   evAcc))
            totTrEAcc.append(((e + 1),  trEAcc))

            # BEGIN Generated by Perplexity.ai.
            if es:
                if avgValLoss < bEvLoss - esd:
                    bEvLoss   = avgValLoss
                    wait      = 0
                    bestState = {k: v.detach().cpu().clone() for k, v in mdl.state_dict().items()}
                    bestEp    = e + 1

                    print('   => Saved state because it is currently the best.')
                else:
                    wait += 1

                    if wait >= patience:
                        print('   => Stopped early due to no improvement in evaluation loss.')

                        break
            # END Generated by Perplexity.ai.

            # Save model.
            if not exists(f'{sout}/models'):
                makedirs(f'{sout}/models')
            state    = {k: v.detach().cpu().clone() for k, v in mdl.state_dict().items()}
            dummyMdl = ModelType(mer)
            dummyMdl.load_state_dict(state)
            pytorch.save(dummyMdl.state_dict(), f'{sout}/models/Model_Id{n}_Cl{mdl.__class__.__name__}_Ep{e + 1}.tmdl')
    except KeyboardInterrupt:
        print('Stopped training due to user interaction.')
    print('Finished training.')

    if bestState is not None:
        mdl.load_state_dict(bestState)

    # Output all statistics.
    endT = datetime.now()
    int_OutputEvaluationStatistics(
        sout,
        nam,
        endT - startT,
        bestEp,
        hyperP,
        dsSt, # Any dataset stats should be fine; the stats for both are the same.
        (totTrLoss, totEvLoss, totTrELoss),
        (totTrAcc,  totEvAcc, totTrEAcc),
        (totTYReal, totTYPred, totEYReal, totEYPred, totTEYReal, totTEYPred),
        epStats
    )

    # Save best model.
    bname = join(sout, f'Model_{n}_Best_Ep{bestEp}.tmdl')
    pytorch.save(mdl.state_dict(), bname)
    print(f'Saved best model (from epoch {bestEp}) under "{bname}".')
    exit(0)


